services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Development service with hot reload
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
    restart: unless-stopped

networks:
  default:
    name: movie-browser-network
